"""Generate src/flights/tables.ts from flight-service/app/normalize.py.

The Android app's flight engine (a TypeScript port of flight-service) needs the same lookup
tables: airlines, aircraft type names, helicopter types, status rules. Re-run this after
changing them in Python so the two stay identical.

Usage (from app/android/):  python scripts/gen_tables.py
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent
sys.path.insert(0, str(ROOT / "flight-service"))

from app import normalize as n  # noqa: E402

OUT = HERE.parent / "src" / "flights" / "tables.ts"


def record(name: str, d: dict, doc: str) -> str:
    rows = "".join(f"  {json.dumps(k)}: {json.dumps(v)},\n" for k, v in d.items())
    return f"/** {doc} */\nexport const {name}: Record<string, string> = {{\n{rows}}};\n"


def string_set(name: str, items, doc: str) -> str:
    rows = "".join(f"  {json.dumps(v)},\n" for v in sorted(items))
    return f"/** {doc} */\nexport const {name}: ReadonlySet<string> = new Set([\n{rows}]);\n"


def string_list(name: str, items, doc: str) -> str:
    rows = "".join(f"  {json.dumps(v)},\n" for v in items)
    return f"/** {doc} */\nexport const {name}: readonly string[] = [\n{rows}];\n"


parts = [
    "// GENERATED by scripts/gen_tables.py from flight-service/app/normalize.py. Don't edit by hand:\n"
    "// change the Python tables, then run `python scripts/gen_tables.py` in app/android/.\n",
    record("AIRLINES", n.AIRLINES, "ICAO airline prefix of a callsign -> airline name."),
    record("TYPE_NAMES", n.TYPE_NAMES, "ICAO type designator -> human-readable aircraft name."),
    string_set("HELICOPTER_TYPES", n.HELICOPTER_TYPES, "Helicopter type designators, for aircraft that don't broadcast category A7."),
    string_set("EMERGENCY_STATUSES", n.EMERGENCY_STATUSES, "readsb `emergency` values that are real emergencies (not \"lifeguard\")."),
    record("EMERGENCY_SQUAWKS", n.EMERGENCY_SQUAWKS, "Emergency squawk codes, used when the emergency field isn't set."),
    string_list("MEDICAL_CALLSIGN_PREFIXES", n.MEDICAL_CALLSIGN_PREFIXES, "Air-ambulance callsign prefixes."),
    f"/** adsb.lol dbFlags bit for military aircraft. */\nexport const DBFLAG_MILITARY = {n.DBFLAG_MILITARY};\n",
]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(parts), encoding="utf-8", newline="\n")
print(f"wrote {OUT.relative_to(ROOT)}")
